In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
ar = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
a.shape

(9,)

In [10]:
ar.shape

(2, 5)

In [11]:
arr.shape

(3, 3)

In [12]:
ar


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
a.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
new_ar = ar.reshape(5,2)

In [18]:
new_ar

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
new_ar[0][1]+new_ar[1][1]

6

In [26]:
new_ar[0][1]


2

In [27]:
new_ar[1][0] + new_ar[3][1]

11

In [28]:
A

NameError: name 'A' is not defined

In [29]:
A

NameError: name 'A' is not defined

In [30]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
for x in a:
    print(x)

1
2
3
4
5
6
7
8
9


In [32]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
for x in ar:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [34]:
new_ar

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [35]:
for x in new_ar:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [36]:
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[2:4]

array([3, 4])

In [42]:
a[2:4:2]

array([3])

In [46]:
ar[0,2:4]

array([3, 4])

In [50]:
arr[0,1:7]

array([2, 3])

In [51]:
a.where(n == 3)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [52]:
x = np.where(a == 3)

In [53]:
y = np.where(a == 8)

In [54]:
x

(array([2], dtype=int64),)

In [55]:
y

(array([7], dtype=int64),)

In [56]:
x = a.sort()

In [57]:
x