### IMPORT THE DATASET

In [1]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### SPLIT THE DATASET INTO TRAINING AND TESTING DATA

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train ,x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [10]:
x_train

array([[6.7, 3.3, 5.7, 2.1],
       [7.7, 2.8, 6.7, 2. ],
       [7.4, 2.8, 6.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.9, 4.3, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 5.6, 2.4],
       [6.2, 2.2, 4.5, 1.5],
       [5.7, 4.4, 1.5, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.4, 2.8, 5.6, 2.2],
       [7.1, 3. , 5.9, 2.1],
       [5. , 3. , 1.6, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [7.2, 3. , 5.8, 1.6],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [6.3, 3.4, 5.6, 2.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.5, 3. , 5.2, 2. ],
       [5.1, 3.5, 1.4, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [6.1, 2

In [11]:
y_train

array([2, 2, 2, 1, 2, 1, 0, 2, 0, 1, 2, 1, 0, 1, 1, 2, 2, 1, 0, 2, 2, 1,
       2, 2, 0, 1, 2, 0, 1, 2, 0, 2, 0, 0, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0,
       2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 2,
       2, 1, 0, 2, 1, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 1, 2, 0,
       2, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1,
       0, 0, 2, 1, 0, 2, 1, 0, 1, 0])

### Create ANN Model using Tensorflow and Keras

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential()


In [14]:
input_layer = Dense(16, input_shape =(4,))

In [15]:
model.add(input_layer)

In [16]:
hidden_layer1 = Dense(16, activation='relu')

In [17]:
model.add(hidden_layer1)

In [18]:
hidden_layer2 = Dense(16, activation='relu')

In [19]:
model.add(hidden_layer2)

In [20]:
output_layer = Dense(3, activation='softmax')

In [21]:
model.add(output_layer)

### Compile The Model

In [22]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Train Model

In [23]:
model.fit(x_train, y_train, epochs=300, batch_size=16)

Epoch 1/300
8/8 [==============================] - 1s 2ms/step - loss: 1.9788 - accuracy: 0.5917
Epoch 2/300
8/8 [==============================] - 0s 5ms/step - loss: 1.5599 - accuracy: 0.7000
Epoch 3/300
8/8 [==============================] - 0s 2ms/step - loss: 1.2719 - accuracy: 0.6500
Epoch 4/300
8/8 [==============================] - 0s 3ms/step - loss: 1.0570 - accuracy: 0.4917
Epoch 5/300
8/8 [==============================] - 0s 7ms/step - loss: 0.9752 - accuracy: 0.6167
Epoch 6/300
8/8 [==============================] - 0s 2ms/step - loss: 0.9163 - accuracy: 0.7500
Epoch 7/300
8/8 [==============================] - 0s 4ms/step - loss: 0.8712 - accuracy: 0.7250
Epoch 8/300
8/8 [==============================] - 0s 5ms/step - loss: 0.8199 - accuracy: 0.7417
Epoch 9/300
8/8 [==============================] - 0s 838us/step - loss: 0.7640 - accuracy: 0.7583
Epoch 10/300
8/8 [==============================] - 0s 3ms/step - loss: 0.7162 - accuracy: 0.7917
Epoch 11/300
8/8 [=========

8/8 [==============================] - 0s 5ms/step - loss: 0.0773 - accuracy: 0.9750
Epoch 85/300
8/8 [==============================] - 0s 6ms/step - loss: 0.0734 - accuracy: 0.9750
Epoch 86/300
8/8 [==============================] - 0s 6ms/step - loss: 0.0841 - accuracy: 0.9667
Epoch 87/300
8/8 [==============================] - 0s 702us/step - loss: 0.0803 - accuracy: 0.9667
Epoch 88/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0745 - accuracy: 0.9750
Epoch 89/300
8/8 [==============================] - 0s 3ms/step - loss: 0.0800 - accuracy: 0.9750
Epoch 90/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0782 - accuracy: 0.9667
Epoch 91/300
8/8 [==============================] - 0s 706us/step - loss: 0.0726 - accuracy: 0.9750
Epoch 92/300
8/8 [==============================] - 0s 4ms/step - loss: 0.0749 - accuracy: 0.9667
Epoch 93/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0716 - accuracy: 0.9833
Epoch 94/300
8/8 [===========

8/8 [==============================] - 0s 852us/step - loss: 0.0608 - accuracy: 0.9833
Epoch 167/300
8/8 [==============================] - 0s 756us/step - loss: 0.0604 - accuracy: 0.9833
Epoch 168/300
8/8 [==============================] - 0s 563us/step - loss: 0.0749 - accuracy: 0.9667
Epoch 169/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0775 - accuracy: 0.9750
Epoch 170/300
8/8 [==============================] - 0s 5ms/step - loss: 0.0673 - accuracy: 0.9750
Epoch 171/300
8/8 [==============================] - 0s 317us/step - loss: 0.0530 - accuracy: 0.9833
Epoch 172/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0619 - accuracy: 0.9750
Epoch 173/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0637 - accuracy: 0.9750
Epoch 174/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0568 - accuracy: 0.9833
Epoch 175/300
8/8 [==============================] - 0s 4ms/step - loss: 0.0596 - accuracy: 0.9750
Epoch 176/300
8/

8/8 [==============================] - 0s 5ms/step - loss: 0.0531 - accuracy: 0.9833
Epoch 249/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0594 - accuracy: 0.9833
Epoch 250/300
8/8 [==============================] - 0s 970us/step - loss: 0.0608 - accuracy: 0.9750
Epoch 251/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0675 - accuracy: 0.9750
Epoch 252/300
8/8 [==============================] - 0s 3ms/step - loss: 0.0559 - accuracy: 0.9750
Epoch 253/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0711 - accuracy: 0.9750
Epoch 254/300
8/8 [==============================] - 0s 3ms/step - loss: 0.0586 - accuracy: 0.9750
Epoch 255/300
8/8 [==============================] - 0s 382us/step - loss: 0.0534 - accuracy: 0.9833
Epoch 256/300
8/8 [==============================] - 0s 3ms/step - loss: 0.0490 - accuracy: 0.9750
Epoch 257/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0546 - accuracy: 0.9750
Epoch 258/300
8/8 [=

### Evaluate the ANN Model 

In [24]:
val_loss , val_acc = model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 266ms/step - loss: 0.0688 - accuracy: 0.9667


### Making Predictions with new data

In [25]:
arr = np.array([[5.1, 3.5, 1.4, 0.2]])

In [26]:
result = model.predict(arr)

1/1 [==============================] - 0s 114ms/step


In [27]:
result

array([[9.9998844e-01, 1.1621565e-05, 1.8033455e-11]], dtype=float32)

In [28]:
np.argmax(result)

0