### IMPORT THE DATASET

In [45]:
from sklearn.datasets import load_iris
import numpy as np

In [3]:
iris = load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### SPLIT THE DATASET INTO TRAINING AND TESTING DATA

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train ,x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [16]:
x_train

array([[4.8, 3. , 1.4, 0.1],
       [5.7, 2.9, 4.2, 1.3],
       [5.8, 4. , 1.2, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.4, 1.4, 0.3],
       [6.1, 3. , 4.6, 1.4],
       [7.7, 3.8, 6.7, 2.2],
       [5.1, 3.5, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [5.7, 2.8, 4.1, 1.3],
       [6. , 2.9, 4.5, 1.5],
       [5.1, 3.8, 1.5, 0.3],
       [5.7, 3. , 4.2, 1.2],
       [6.3, 3.3, 4.7, 1.6],
       [4.7, 3.2, 1.6, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.9, 3.1, 5.1, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 2.9, 4.3, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.4, 3.9, 1.7, 0.4],
       [7.7, 3. , 6.1, 2.3],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 2. , 3.5, 1. ],
       [5.2, 2.7, 3.9, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [6.4, 3.1, 5.5, 1.8],
       [4.6, 3

In [17]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 2, 1, 0,
       1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 1, 2, 0, 2, 1, 1, 2,
       0, 0, 0, 0, 2, 1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1,
       1, 0, 2, 2, 2, 2, 2, 2, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 2,
       1, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0,
       0, 2, 0, 2, 2, 2, 1, 2, 2, 0])

### Create ANN Model using Tensorflow and Keras

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [34]:
model = Sequential()


In [35]:
input_layer = Dense(4, input_shape =(4,))

In [36]:
model.add(input_layer)

In [37]:
hidden_layer = Dense(4, activation='relu')

In [38]:
model.add(hidden_layer)

In [39]:
output_layer = Dense(3, activation='softmax')

In [40]:
model.add(output_layer)

### Compile The Model

In [41]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Train Model

In [42]:
model.fit(x_train, y_train, epochs=300, batch_size=4)

Epoch 1/300
30/30 [==============================] - 3s 6ms/step - loss: 2.4176 - accuracy: 0.0000e+00
Epoch 2/300
30/30 [==============================] - 0s 2ms/step - loss: 1.9013 - accuracy: 0.1000
Epoch 3/300
30/30 [==============================] - 0s 2ms/step - loss: 1.7118 - accuracy: 0.3250
Epoch 4/300
30/30 [==============================] - 0s 2ms/step - loss: 1.6222 - accuracy: 0.3500
Epoch 5/300
30/30 [==============================] - 0s 2ms/step - loss: 1.5474 - accuracy: 0.3500
Epoch 6/300
30/30 [==============================] - 0s 2ms/step - loss: 1.4811 - accuracy: 0.3500
Epoch 7/300
30/30 [==============================] - 0s 2ms/step - loss: 1.3923 - accuracy: 0.3500
Epoch 8/300
30/30 [==============================] - 0s 1ms/step - loss: 1.2744 - accuracy: 0.3500
Epoch 9/300
30/30 [==============================] - 0s 2ms/step - loss: 1.1669 - accuracy: 0.3500
Epoch 10/300
30/30 [==============================] - 0s 2ms/step - loss: 1.0515 - accuracy: 0.3500
Epoch

Epoch 83/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1142 - accuracy: 0.9750
Epoch 84/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1090 - accuracy: 0.9833
Epoch 85/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1169 - accuracy: 0.9500
Epoch 86/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1062 - accuracy: 0.9750
Epoch 87/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1046 - accuracy: 0.9750
Epoch 88/300
30/30 [==============================] - 0s 1ms/step - loss: 0.1026 - accuracy: 0.9750
Epoch 89/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1031 - accuracy: 0.9667
Epoch 90/300
30/30 [==============================] - 0s 1ms/step - loss: 0.1041 - accuracy: 0.9667
Epoch 91/300
30/30 [==============================] - 0s 2ms/step - loss: 0.1002 - accuracy: 0.9583
Epoch 92/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0978 - accuracy: 0.9750


30/30 [==============================] - 0s 2ms/step - loss: 0.0626 - accuracy: 0.9750
Epoch 165/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0610 - accuracy: 0.9833
Epoch 166/300
30/30 [==============================] - 0s 1ms/step - loss: 0.0605 - accuracy: 0.9667
Epoch 167/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0645 - accuracy: 0.9750
Epoch 168/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0611 - accuracy: 0.9833
Epoch 169/300
30/30 [==============================] - 0s 1ms/step - loss: 0.0593 - accuracy: 0.9833
Epoch 170/300
30/30 [==============================] - 0s 3ms/step - loss: 0.0589 - accuracy: 0.9833
Epoch 171/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0595 - accuracy: 0.9833
Epoch 172/300
30/30 [==============================] - 0s 3ms/step - loss: 0.0606 - accuracy: 0.9917
Epoch 173/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0599 - accuracy: 0.9833
Epoc

30/30 [==============================] - 0s 2ms/step - loss: 0.0533 - accuracy: 0.9750
Epoch 246/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0513 - accuracy: 0.9917
Epoch 247/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0530 - accuracy: 0.9750
Epoch 248/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0545 - accuracy: 0.9833
Epoch 249/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0562 - accuracy: 0.9750
Epoch 250/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0511 - accuracy: 0.9833
Epoch 251/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0519 - accuracy: 0.9750
Epoch 252/300
30/30 [==============================] - 0s 3ms/step - loss: 0.0595 - accuracy: 0.9833
Epoch 253/300
30/30 [==============================] - 0s 3ms/step - loss: 0.0621 - accuracy: 0.9667
Epoch 254/300
30/30 [==============================] - 0s 2ms/step - loss: 0.0487 - accuracy: 0.9917
Epoc

### Evaluate the ANN Model 

In [43]:
val_loss , val_acc = model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 273ms/step - loss: 0.1719 - accuracy: 0.9333


### Making Predictions with new data

In [46]:
arr = np.array([[5.1, 3.5, 1.4, 0.2]])

In [49]:
result = model.predict(arr)

1/1 [==============================] - 0s 109ms/step


In [50]:
result

array([[9.9994886e-01, 5.1123112e-05, 2.9809624e-21]], dtype=float32)

In [51]:
np.argmax(result)

0