In [65]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [17]:
tf.__version__

'2.13.0'

In [18]:
a = 1                                            

In [19]:
b=2

In [21]:
c = a + b

In [22]:
c

3

In [24]:
c1 = tf.constant(10)

In [26]:
c1


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [27]:
c1 = tf.constant(10,tf.int16)

In [28]:
c1

<tf.Tensor: shape=(), dtype=int16, numpy=10>

In [30]:
c1 = tf.constant(10,tf.int16,name="MY Var")

In [31]:
 c1

<tf.Tensor: shape=(), dtype=int16, numpy=10>

In [32]:
c1 = tf.constant("HELLOW JAY")

In [33]:
c1

<tf.Tensor: shape=(), dtype=string, numpy=b'HELLOW JAY'>

In [52]:
t1 = tf.Variable(23)

In [53]:
t1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [54]:
t1.assign(13)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=13>

In [55]:
t1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=13>

In [56]:
a = tf.constant(19)
b = tf.constant(24)

In [57]:
c = a +b

In [58]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [59]:
sess = tf.compat.v1.Session()

In [60]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [64]:
print(sess.run(c))

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [71]:
c = tf.add(a,b)

In [72]:
sess.run(c)

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [70]:
c =tf.add(a, b)

In [79]:
x = tf.constant(10.5, name="x")
y = tf.constant(3.0, name="y")

In [80]:
res = tf.pow(x, y, name="result")

In [81]:
res

<tf.Tensor: shape=(), dtype=float32, numpy=1157.625>

In [77]:
with tf.compat.v1.Session() as sess:
    x = tf.constant(10.5, name="x")
    y = tf.constant(3.0, name="y")
    res = tf.pow(x, y, name="result")
    
    output = sess.run(res)

In [78]:
output

1157.625

In [86]:
with tf.compat.v1.Session() as sess:
    x = tf.compat.v1.placeholder(tf.float32)
    y = tf.compat.v1.placeholder(tf.float32)
    z = x + y
    output1 = sess.run(z, feed_dict = {x:3,y:5.5})
    output2 = sess.run(z, feed_dict = {x:[1,2],y:[4,3]})

In [87]:
output1

8.5

In [88]:
output2

array([5., 5.], dtype=float32)