In [30]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [31]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [32]:
z = x +y

In [33]:
z


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [34]:
z= tf.tensordot(x,y,axes=1)

In [35]:
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [36]:
z = x** 5

In [37]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243])>

In [38]:
x = tf.range(9)

In [39]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [40]:
x = tf.reshape(x , (3,3))

In [41]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [42]:
x= tf.transpose(x, perm=[1,0])

In [43]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>